language: python

python:
    - "2.7"

services:
    - mongodb

install:
    - pip install -q coveralls --use-mirrors
    - pip install -r tests/requirements.txt
    - pip install flake8

before_script:
    - flake8 origins
    - mysql -u travis < tests/data/chinook_mysql.sql > /dev/null
    - psql -U postgres -c 'create database chinook' > /dev/null
    - psql -U postgres -d chinook < tests/data/chinook_postgresql.sql > /dev/null
    - mongorestore --db chinook tests/data/mongodb > /dev/null

script:
    - coverage run test_suite.py

after_success:
    - coveralls
