language: python
python:
    - "2.7"
install:
    - pip install -q coveralls --use-mirrors
    - pip install -r tests/requirements.txt
    - pip install flake8
before_script:
    flake8 origins
script:
    - coverage run test_suite.py
after_success:
    - coveralls
